#image: sagemath/sagemath-dev:latest

branches:
  only:
    - master

services:
  - docker

before-install:
  - docker pull sagemath/sagemath-dev:latest

#install:
#  - sage -pip install .

script:
   - docker run -v$(pwd):/train_track sagemath/sagemath-dev:latest /bin/sh -c "sage -pip install /train_track; sage -t --force-lib /train_track/train_track"